apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: akeso-app
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017      # External port
      targetPort: 27017 # Container port
  type: ClusterIP      # Internal communication only