apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: akeso-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000       # External port
      targetPort: 5000  # Container port
  type: NodePort       # Change to LoadBalancer if using cloud